name: disaster_response_flutter
description: Offline-First Intelligent Disaster Response Citizen & Responder Mobile App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.0
  uuid: ^4.3.3
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  drift: ^2.31.0
  sqlite3_flutter_libs: ^0.5.42
  path_provider: ^2.1.5
  path: ^1.9.1
  connectivity_plus: ^7.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  drift_dev: ^2.31.0
  build_runner: ^2.15.1

flutter:
  uses-material-design: true
